### ISSUE TITLE
Allow multiple preference classes for a single build variant

### ISSUE THREAD

**Issue by fredpedersen** [Flipboard/psync#12]
I use separate SharedPreferences for each appwidget the user creates. I would like to be able to be able to configure Psync to generate two preference classes: P.java for my global application settings, and W.java for my widget specific settings which I can set up using `W.setSharedPreferences(widgetPrefs)`.

I imagine it could work something like this:

```
psync {
    varient{
        className = "P"
        includesPattern = "**/xml/app_prefs.xml"
        packageName = "com.example.myapp"
    }
    varient{
        className = "W"
        includesPattern = "**/xml/widget_*.xml"
        packageName = "com.example.myapp"
    }
}
```

**Comment by ZacSweers** [comment]
This is doable, but I'm not sure what the benefits are beyond high level separation, which I think could be just as easily served with prefixes. Is there anything else you'd expect to gain with this?

**Comment by fredpedersen** [comment]
The ability to use two separate shared preference files simultaneously. 

For example, in my app I use the default shared preferences file as loaded by `P.init();` for app wide settings. When a user adds a new appwidget, I create a new shared preferences file for that specific widget. This enables me to use a PreferenceFragment in my configuration activity and have that handle setting the preferences. 

When updating the appwidget I need to use some of the app wide settings in combination with the appwidget specific settings. Currently I would need to do something like this:

```
SharedPreferences globalPreferences = PreferenceManager.getDefaultSharedPreferences(context);
SharedPreferences widgetPreferences = context.getSharedPreferences(
        context.getPackageName() + appWidgetId,
        Context.MODE_PRIVATE);

P.setSharedPreferences(globalPreferences);
//... use global preference
P.setSharedPreferences(widgetPreferences);
//... use widget preference
P.setSharedPreferences(globalPreferences);
//... use global preference
```

This gets messy pretty quickly. I would prefer to do this once:

```
W.init(context.getApplicationContext());
W.setSharedPreferences(prefs);

P.globalPreference.get();
W.widgetPreference.get();
```

**Comment by ZacSweers** [comment]
This issue was moved to hzsweers/psync#10
