### ISSUE TITLE
Batch editing API

### ISSUE THREAD

**Issue by ZacSweers** [Flipboard/psync#3]
Discussed this with someone on reddit. This _should_ be safe, because commits to memory are done in a synchronized block and then clears the "mModified" map. Only question for me is that if it's safe for reuse, why doesn't `SharedPreferencesImpl` do it? Currently it returns a new `EditorImpl` every time you call `edit()`.

@markrietveld @GHawk1ns @petershu thoughts?

**Comment by markrietveld** [comment]
I think PSync should have some form of batch updates. If you're updating a bunch of values at once, you don't want a separate edit() and apply() call for each of those. I don't think we should have a single editor for the life of the app though

I don't have a specific API in mind right now, but we can come up with a proposal. In the mean time, other proposals are welcome too

**Comment by ZacSweers** [comment]
This issue was moved to hzsweers/psync#3
