### ISSUE TITLE
long support

### ISSUE THREAD

**Issue by stoyicker** [Flipboard/psync#6]
Unless I'm missing something, preferences default to being integers when the default value is an integer, and trying to specify something like 1L won't really make it (probably intended I'm guessing?). It would be nice if there was a way to state that the preference is desired to be a long instead, or if methods for setting and retrieval of the preference as both long and int were generated.

**Comment by ZacSweers** [comment]
Would this be solved by #2?

**Comment by stoyicker** [comment]
Yep, my bad. Closing.

**Comment by ZacSweers** [comment]
:+1: Planning to try to add support for that soon. I've personally switched jobs and haven't actually needed to do anything with preferences in some time, so this hasn't personally been a high priority for me. Enough people have asked for it though that I should give it a proper dusting off.
